Update Sampler documentation
gaelcolas/Sampler pull request #321
Opened 2021-08-21 13:28 UTC by johlju

# Pull Request

## Pull Request (PR) description

### Changed
- Updated Sampler documentation.

## Task list

- [x] The PR represents a single logical change. i.e. Cosmetic updates should go in different PRs.
- [x] Added an entry under the Unreleased section of in the CHANGELOG.md as per [format](https://keepachangelog.com/en/1.0.0/).
- [x] Local clean build passes without issue or fail tests (`build.ps1 -ResolveDependency`).
- [x] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

2021-09-03 18:51 UTC, johlju commented
I'm thinking maybe we should move the sections "Commands for Build Tasks" and "Build Task Variables" (and the future section "Build Tasks") to a CONTRIBUTION.md instead. 🤔

2021-09-04 06:33 UTC, PlagueHO requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/321)* status: all files reviewed, 47 unresolved discussions (waiting on @johlju)

___
*[README.md, line 10 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijFsSr7FFdFPugJ9Af:-MijFsSr7FFdFPugJ9Ag:b6j3m4u) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L10)):*
> ```
> This project is used to scaffold a PowerShell module project, complete with
> PowerShell build and deploy pipeline automation.
> ```
___
*[README.md, line 17 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijH7T-1oJMZY9_276g:-MijH7T-1oJMZY9_276h:b2y25hf) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L17)):*
> ```
> - Help building your module by adding elaborate sample elements like classes,
>   MOF-based DSC resources, class-based DSC resources, helper modules, embedded helper
>   modules, and more.
> ```
___
*[README.md, line 20 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijHJta88ZNn3_rUlIC:-MijHJta88ZNn3_rUlID:b4ymmxh) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L20)):*
> ```
> - Avoid the "it works on my machine" and remove the dependence on specific tools
>   (such as a CI tool).
> ```
___
*[README.md, line 24 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijHWRdDMVIOqeb64AC:-MijHWRdDMVIOqeb64AD:b5jnxyb) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L24)):*
> ```
> - Assume nothing is set up, and you don't have local administrator rights.
> ```
___
*[README.md, line 25 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijHbai68BNtOaQNU68:-MijHbai68BNtOaQNU69:bk4d1vw) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L25)):*
> ```
> - Works on Windows, Linux and MacOS.
> ```
___
*[README.md, line 29 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijHjJ84KxVBY0gZQ-P:-MijHjJ84KxVBY0gZQ-Q:bhh3pa1) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L29)):*
> ```
> > _Note: The video was made when Sampler was in early stages. Since that time_
> > _there have been a lot of improvements and changes, so please read the_
> > _ documentation below._
> ```
___
*[README.md, line 45 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijIGZR48Ds3eybN598:-MijIGZR48Ds3eybN599:b-yeiul0) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L45)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> Managing the versions of your module is tedious, and is hard to maintain
> consistency over time. The usual tricks like checking what the latest version on
> PowerShell Gallery is, or use the `BuildNumber` to increment a `0.0.x` version
> works but isn't ideal, especially if we want to stick to [semver](https://semver.org/).
> ```
</details>

___
*[README.md, line 53 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijIcGq2zymW3TR5oyL:-MijIcGq2zymW3TR5oyM:b-ljbpu4) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L53)):*
> ```
> the best method is to rely on the cross-platform tool [`GitVersion`](https://gitversion.net/docs/).
> ```
___
*[README.md, line 58 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijKWRC0jgSrSmVsBWc:-MijKWRC0jgSrSmVsBWd:b6xjlyj) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L58)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> Generally, GitVersion will look at the latest version tag, the branch names, commit
> messages, to try to determine the Major/Minor/Patch (semantic versioning) based
> on detected change (configurable in the file [`GitVersion.yml`](https://gitversion.net/docs/reference/configuration)
> that is part of your project).
> ```
</details>

___
*[README.md, line 64 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijKrsc5z2nNEwhGC6K:-MijKrsc5z2nNEwhGC6L:b-6mgyv2) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L64)):*
> ```
> Therefore, it is recommended that you install `GitVersion` on your development environment
> and on your CI environment build agents.
> ```
___
*[README.md, line 67 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijLDxBDRnAUUX_NrUt:-MijLDxBDRnAUUX_NrUu:b8z5d6q) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L67)):*
> ```
There are various ways to [install GitVersion](https://gitversion.net/docs/usage/cli/installation)
> on your development environment. If you use Chocolatey (install and upgrade):
> ```
___
*[README.md, line 74 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijL_tw5M07NQxlQCS9:-MijL_tw5M07NQxlQCSA:b-kc4qr2) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L74)):*
> ```
> This describes how to [install GitVersion in your CI environment build agents](https://gitversion.net/docs/usage/ci)
> if you plan to use the deploy pipelines in the CI.
> ```
___
*[README.md, line 84 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijLoQ24_ozTUs02bJj:-MijLoQ24_ozTUs02bJk:bpf4mlf) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L84)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> To create a new project the command `New-SampleModule` should be used. Depending
> on the template used with the command the content in project will contain
> different sample content while some also adds additional pipeline jobs. But all templates
> (expect one) will have the basic tasks to have a working pipeline including build, test and deploy stages.
> ```
</details>

___
*[README.md, line 86 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijLzkL4Sb59QNLqjeZ:-MijLzkL4Sb59QNLqje_:b-2reztz) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L86)):*
> ```
> The sections below show how to use each template. The templates are:
> ```
___
*[README.md, line 96 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijMEQT2b9nQk4YrS_-:-MijMEQT2b9nQk4YrS_0:brk7x6f) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L96)):*
> ```Markdown
> - `GCPackage` - Creates a module that can be deployed to be used with _Azure Policy_
>   _Guest Configuration_.
>   
> ```

Remove ...
___
*[README.md, line 99 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijMLrS64iyVQVFmUHO:-MijMLrS64iyVQVFmUHP:boaao42) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L99)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> As per the video above, you can create a new module project with all files and
> pipeline scripts. Once the project is created, the `build.ps1` inside the new
> project folder is how you interact with the built-in pipeline automation, and
> the file `build.yaml` is where you configure and customize it.
> ```
</details>

___
*[README.md, line 201 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijMc1b76ZLSfFFKVzB:-MijMc1b76ZLSfFFKVzC:b-zbvxq1) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L201)):*
> ```
> ### How to download dependencies for the project
> ```
___
*[README.md, line 203 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijMhBu4cxNVOcATdEj:-MijMhBx1-6InQhXgXmS:byrch9l)  [...]

2021-09-04 14:10 UTC, johlju reviewed
Thanks for the review! Much better after your proof reading. :smiley: 

> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/321#-:-Mil8D817aEKfDXHsHFT:bwhjado)* status: 1 of 2 files reviewed, 47 unresolved discussions (waiting on @PlagueHO)

___
*[README.md, line 10 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijFsSr7FFdFPugJ9Af:-Mil600B-ZKq_HoSSmfh:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L10)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

> ```
> This project is used to scaffold a PowerShell module project, complete with
> PowerShell build and deploy pipeline automation.
> ```

</blockquote></details>

Done.
___
*[README.md, line 17 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijH7T-1oJMZY9_276g:-Mil63B98BfvDEjrAX0u:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L17)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

> ```
> - Help building your module by adding elaborate sample elements like classes,
>   MOF-based DSC resources, class-based DSC resources, helper modules, embedded helper
>   modules, and more.
> ```

</blockquote></details>

Done.
___
*[README.md, line 20 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijHJta88ZNn3_rUlIC:-Mil65MiBB0Z1d2iNmtl:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L20)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

> ```
> - Avoid the "it works on my machine" and remove the dependence on specific tools
>   (such as a CI tool).
> ```

</blockquote></details>

Done.
___
*[README.md, line 24 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijHWRdDMVIOqeb64AC:-Mil669NC3NAbsYG08Wv:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L24)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

> ```
> - Assume nothing is set up, and you don't have local administrator rights.
> ```

</blockquote></details>

Done.
___
*[README.md, line 25 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijHbai68BNtOaQNU68:-Mil66nUBf-U8OUbRJ3n:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L25)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

> ```
> - Works on Windows, Linux and MacOS.
> ```

</blockquote></details>

Done.
___
*[README.md, line 29 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijHjJ84KxVBY0gZQ-P:-Mil68Yr8itlO23uDsGS:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L29)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

> ```
> > _Note: The video was made when Sampler was in early stages. Since that time_
> > _there have been a lot of improvements and changes, so please read the_
> > _ documentation below._
> ```

</blockquote></details>

Done.
___
*[README.md, line 45 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijIGZR48Ds3eybN598:-Mil6E443xnfGEuu73c2:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L45)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

> ```
> Managing the versions of your module is tedious, and is hard to maintain
> consistency over time. The usual tricks like checking what the latest version on
> PowerShell Gallery is, or use the `BuildNumber` to increment a `0.0.x` version
> works but isn't ideal, especially if we want to stick to [semver](https://semver.org/).
> ```

</blockquote></details>

Done.
___
*[README.md, line 53 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijIcGq2zymW3TR5oyL:-Mil6Fes18xr0Pqj5FZg:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L53)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

> ```
> the best method is to rely on the cross-platform tool [`GitVersion`](https://gitversion.net/docs/).
> ```

</blockquote></details>

Done.
___
*[README.md, line 58 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijKWRC0jgSrSmVsBWc:-Mil6ITF4yYhBTqS-ecy:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L58)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

> ```
> Generally, GitVersion will look at the latest version tag, the branch names, commit
> messages, to try to determine the Major/Minor/Patch (semantic versioning) based
> on detected change (configurable in the file [`GitVersion.yml`](https://gitversion.net/docs/reference/configuration)
> that is part of your project).
> ```

</blockquote></details>

Done.
___
*[README.md, line 64 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijKrsc5z2nNEwhGC6K:-Mil6Jgh4ICcv3qRzXfE:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L64)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

> ```
> Therefore, it is recommended that you install `GitVersion` on your development environment
> and on your CI environment build agents.
> ```

</blockquote></details>

Done.
___
*[README.md, line 67 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijLDxBDRnAUUX_NrUt:-Mil6KyD5GCxWpdNWPfv:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L67)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

> ```
There are various ways to [install GitVersion](https://gitversion.net/docs/usage/cli/installation)
> on your development environment. If you use Chocolatey (install and upgrade):
> ```

</blockquote></details>

Done.
___
*[README.md, line 74 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijL_tw5M07NQxlQCS9:-Mil6M6C8u15TEt9Ke9Y:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L74)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

> ```
> This describes how to [install GitVersion in your CI environment build agents](https://gitversion.net/docs/usage/ci)
> if you plan to use the deploy pipelines in the CI.
> ```

</blockquote></details>

Done.
___
*[README.md, line 84 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijLoQ24_ozTUs02bJj:-Mil6Pte2EB5ploS_pkO:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L84)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

> ```
> To create a new project the command `New-SampleModule` should be used. Depending
> on the template used with the command the content in project will contain
> different sample content while some also adds additional pipeline jobs. But all templates
> (expect one) will have the basic tasks to have a working pipeline including build, test and deploy stages.
> ```

</blockquote></details>

Done.
___
*[README.md, line 86 at r1](https://reviewable.io/reviews/gaelcolas/sampler/321#-MijLzkL4Sb59QNLqjeZ:-Mil6RCT4rgXin1VYJpp:b-896fix) ([raw file](https://github.com/gaelcolas/sampler/blob/fda56ba21faa0a25ef7e38fc4a1848afd59b23f4/README.md#L86)):*
<details><summary><i>Previously, PlagueHO (Danie [...]

2021-09-04 22:36 UTC, PlagueHO approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/321)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johlju)



<!-- Sent from Reviewable.io -->

2021-09-04 22:36 UTC, PlagueHO approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/gaelcolas/sampler/321#-:-Mimx8KN-WWNXylKWEjc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johlju)



<!-- Sent from Reviewable.io -->

2021-09-05 10:08 UTC, merged