Switch to installing GitVersion using dotnet tool install
gaelcolas/Sampler pull request #349
Opened 2022-02-14 08:18 UTC by johlju

# Pull Request

## Pull Request (PR) description

### Changed
- Switch to installing GitVersion using `dotnet tool install`. Fixes [#348](https://github.com/gaelcolas/Sampler/issues/348)
- Updated pipeline to use the build worker image 'ubuntu-latest'.
- Updated the Plaster templates to use 'dotnet tool install' in the pipeline.

## Task list

- [x] The PR represents a single logical change. i.e. Cosmetic updates should go in different PRs.
- [x] Added an entry under the Unreleased section of in the CHANGELOG.md as per [format](https://keepachangelog.com/en/1.0.0/).
- [x] Local clean build passes without issue or fail tests (`build.ps1 -ResolveDependency`).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

2022-02-14 08:18 UTC, johlju commented
Will send in more commits, just want to make sure the pipeline works.

2022-02-16 14:35 UTC, gaelcolas requested changes
One change and it's good to go.

2022-02-16 14:35 UTC, gaelcolas commented on Sampler/Templates/Sampler/azure-pipelines.yml.template
> +              ModuleVersion: $$(NuGetVersionV2)
```suggestion
              ModuleVersion: $(NuGetVersionV2)
```

2022-02-16 14:35 UTC, gaelcolas commented on Sampler/Templates/Sampler/azure-pipelines.yml.template
> +              ModuleVersion: $$(NuGetVersionV2)
Assuming that was a mistake.

2022-02-16 17:01 UTC, gaelcolas approved these changes
ok now, once the build passes.

2022-02-16 18:56 UTC, merged