Refactor `PSResourceGet` implementation in `Resolve-Dependency.ps1`
gaelcolas/Sampler pull request #450
Opened 2023-12-11 19:05 UTC by jimbrig

# Refactor `Resolve-Dependency.ps1` for new `PSResourceGet` Implementation

## Description

- Updated PowerShell docstrings for the script to be correct with regard to the parameters `UsePSResourceGet` and `PSResourceGetVersion`.
- Changed default version to version `1.0.1` (stable release)

***

- [ ] The PR represents a single logical change. i.e. Cosmetic updates should go in different PRs.
- [ ] Added an entry under the Unreleased section of in the CHANGELOG.md as per [format](https://keepachangelog.com/en/1.0.0/).
- [ ] Local clean build passes without issue or fail tests (`build.ps1 -ResolveDependency`).
- [ ] Documentation added/updated in README.md.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

2023-12-13 09:57 UTC, johlju requested changes
Thank you for fixing this! Just a few minor comments.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/Sampler/450#-:-NlXaz-zEGJZ2jIn7Bm1:b-rccszz)* status: all files reviewed, 2 unresolved discussions (waiting on @jimbrig)

*[a discussion](https://reviewable.io/reviews/gaelcolas/Sampler/450#-NlXarmk7Awz4QdnnZp6:-NlXarmk7Awz4QdnnZp7:b-q4n75r) (no related file):*
Please also update the Plaster template files that are used to build new modules:
https://github.com/gaelcolas/Sampler/tree/main/Sampler/Templates/Build 

___
___
*[`Resolve-Dependency.ps1` line 126 at r1](https://reviewable.io/reviews/gaelcolas/Sampler/450#-NlXaQ8P4x73RHNi8VAO:-NlXaQ8Q3FBgvC738Om6:bepwyzw) ([raw file](https://github.com/gaelcolas/Sampler/blob/0fd09e616cd5abc2ad1a496fcd922a59d3b138b0/Resolve-Dependency.ps1#L126)):*
> ```PowerShell
>     [Parameter()]
>     [System.String]
>     $PSResourceGetVersion = '1.0.1'
> ```

We should not have default values here. 

Please change the default version in the config file instead. A user can enable that to have the script default to that version of PSResourceGet: https://github.com/gaelcolas/Sampler/blob/b2fc9fb6841108304ca16b80c57f6f51535defc8/Resolve-Dependency.psd1#L47



_Code quote:_
```PowerShell
$PSResourceGetVersion = '1.0.1'
```


<!-- Sent from Reviewable.io -->

2023-12-13 10:01 UTC, johlju commented
@jimbrig please also update the CHANGELOG's unreleased section for the build to pass.

2023-12-13 10:06 UTC, johlju requested changes
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/Sampler/450)* status: all files reviewed, 3 unresolved discussions (waiting on @jimbrig)

___
*[`Resolve-Dependency.ps1` line 255 at r1](https://reviewable.io/reviews/gaelcolas/Sampler/450#-NlXcurR5zXtxrENCw1C:-NlXcurR5zXtxrENCw1D:bbaazpk) ([raw file](https://github.com/gaelcolas/Sampler/blob/0fd09e616cd5abc2ad1a496fcd922a59d3b138b0/Resolve-Dependency.ps1#L255)):*
> ```PowerShell
>             {
>                 # Default version to use if non is specified in parameter or in configuration.
>                 $PSResourceGetVersion = '0.9.0-rc1'
> ```

Also, update this to 1.0.1 instead of adding a default value to the parameter. By adding a default value to the parameter it will always override any configured version that is set in the config-file. 


<!-- Sent from Reviewable.io -->

2023-12-13 10:07 UTC, johlju requested changes
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/Sampler/450)* status: all files reviewed, 4 unresolved discussions (waiting on @jimbrig)

*[a discussion](https://reviewable.io/reviews/gaelcolas/Sampler/450#-NlXdD4r3hPMSuDXLIAo:-NlXdD4r3hPMSuDXLIAp:b-9l9rxe) (no related file):*
Please update the CHANGELOG's unreleased section.

___


<!-- Sent from Reviewable.io -->

2024-01-09 14:02 UTC, closed without merging

2024-01-09 14:03 UTC, johlju commented
This was resolved in another PR. Thanks for contributing!

2024-02-27 03:06 UTC, jimbrig commented
@johlju apologies just now seeing this (GitHub notifications got bombozzled with dependabot...) but glad to see it ended up getting resolved. Thanks!