Moved large parts of the ReadMe to the Wiki.
gaelcolas/Sampler pull request #488
Opened 2024-08-13 19:54 UTC by DennisL68

# Pull Request

## Pull Request (PR) description

The README.md was getting pretty big so I'd like to move a large part of it to the Wiki instead

### Added
- Gettings-started.md in the Wiki folder [closes #487]

### Changed
- Getting started video updated [closes #487]

### Deprecated

### Security

### Fixed

### Removed

## Task list

- [ ] The PR represents a single logical change. i.e. Cosmetic updates should go in different PRs.
- [ ] Added an entry under the Unreleased section of in the CHANGELOG.md as per [format](https://keepachangelog.com/en/1.0.0/).
- [ ] Local clean build passes without issue or fail tests (`build.ps1 -ResolveDependency`).
- [x] Documentation added/updated in README.md.
- [x] Documentation added/updated in the Wiki.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

2024-08-13 19:58 UTC, DennisL68 commented
I need some help fixing the failed tests.
I didn't touch any code :)

2024-08-14 10:16 UTC, johlju commented
Hmm, seem to be an issue with the task generating help file for public commands, but it should not care about this new markdown file - must be a bug in the task. I will look into it.

2024-08-14 10:49 UTC, johlju commented
So it seems the tasks is run in the wrong order, if you please. In the build.yaml. Can you move the task `Copy_Source_Wiki_Folder` so that is is before the task `Generate_Wiki_Sidebar'

This:
https://github.com/gaelcolas/Sampler/blob/e669ffae8f8cdf07a4e3e2f0361c078aa74d1eff/build.yaml#L131-L142

To this:
```yaml
  docs:
    # The meta task Generate_Wiki_Content is not used so that Linux and macOS is supported
    # - Generate_Conceptual_Help # Used for DSC resources
    - Create_Wiki_Output_Folder
    # - Generate_Markdown_For_DSC_Resources # Used for DSC resources
    - Generate_Markdown_For_Public_Commands
    - Generate_External_Help_File_For_Public_Commands
    - Clean_Markdown_Of_Public_Commands
    - Copy_Source_Wiki_Folder
    - Generate_Wiki_Sidebar
    - Clean_Markdown_Metadata
    - Package_Wiki_Content
```

2024-08-14 10:51 UTC, johlju commented
The build should work after the above change. 

_There is also a similar bug in the module DscResource.DocGenerator, but that won't affect this PR. I will create an issue in DocGenerato repo to track it._

2024-08-14 10:53 UTC, DennisL68 commented
Great. I'll have a go...

2024-08-14 14:39 UTC, DennisL68 commented
Yeay 👍

2024-08-14 15:11 UTC, DennisL68 commented
@johlju, I fixed some typos after the last check passed and now the checks doesn't seem to start up again.

![image](https://github.com/user-attachments/assets/7e18ecb2-4163-4b27-bb39-ab2c72e156d1)

2024-08-14 16:24 UTC, johlju commented
/azp run

2024-08-14 16:25 UTC, johlju commented
> ... and now the checks doesn't seem to start up again.

Temporary glitch in Azure DevOps probably. 🙂

2024-08-19 16:23 UTC, johlju requested changes
> Reviewed 1 of 1 files at r2, 2 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/gaelcolas/Sampler/488)* status: all files reviewed, 6 unresolved discussions (waiting on @DennisL68)

___
*[`Sampler/WikiSource/Getting-started.md` line 824 at r4](https://reviewable.io/reviews/gaelcolas/Sampler/488#-O4fPUI91zeZw-B5xCPi:-O4fPUI91zeZw-B5xCPj:b-2ofn9d) ([raw file](https://github.com/gaelcolas/Sampler/blob/0f6b04d0d0de5f47dec739209be6c258c93bdd39/Sampler/WikiSource/Getting-started.md#L824)):*
> ```Markdown
>    `output\GCPolicyPackages\UserAmyNotPresent`.
> 
> ## Commands
> ```

All these commands (se below) have documentation that should be moved to each commands comment-based help (if it is not already there). By adding this documentaton to each commands comment-based help it would automatically create wiki documentation.
___
*[`Sampler/WikiSource/Getting-started.md` line 1637 at r4](https://reviewable.io/reviews/gaelcolas/Sampler/488#-O4fPyXiAqRQgq2Uutk4:-O4fPyXiAqRQgq2Uutk5:b7ksj38) ([raw file](https://github.com/gaelcolas/Sampler/blob/0f6b04d0d0de5f47dec739209be6c258c93bdd39/Sampler/WikiSource/Getting-started.md#L1637)):*
> ```Markdown
> the updated statistics.
> 
> ## Build Task Variables
> ```

This entire section and child sections should probably be a separate markdown file in WikiSource.
___
*[`Sampler/WikiSource/Getting-started.md` line 1721 at r4](https://reviewable.io/reviews/gaelcolas/Sampler/488#-O4fQDWS3RtpxadsBMaY:-O4fQDWS3RtpxadsBMaZ:b-o825pz) ([raw file](https://github.com/gaelcolas/Sampler/blob/0f6b04d0d0de5f47dec739209be6c258c93bdd39/Sampler/WikiSource/Getting-started.md#L1721)):*
> ```Markdown
> the same name as the module.
> 
> ## Tasks
> ```

Each task here should have its own markdown file in WikiSource, and each file should have a markdown metadata set to (top of the markdown file):

```
---
Category: Tasks
Type: Documentation
---
```

This would generate a Tasks category in the wiki sidebar during build.
___
*[`Sampler/WikiSource/Home.md` line 13 at r4](https://reviewable.io/reviews/gaelcolas/Sampler/488#-O4fRCkq4taiets_FI1a:-O4fRCkrBaq9c2I_vV2R:b-5wc7sd) ([raw file](https://github.com/gaelcolas/Sampler/blob/0f6b04d0d0de5f47dec739209be6c258c93bdd39/Sampler/WikiSource/Home.md#L13)):*
> ```Markdown
> ## Getting started
> 
> See the section [[Getting started]]
> ```

This line should end with full stop (`.`).



_Suggestion:_
```Markdown
See the section [[Getting started]].
```
___
*[`Sampler/WikiSource/Home.md` line 17 at r4](https://reviewable.io/reviews/gaelcolas/Sampler/488#-O4fRFEK6bwZUOaiooE7:-O4fRFEK6bwZUOaiooE8:undefined) ([raw file](https://github.com/gaelcolas/Sampler/blob/0f6b04d0d0de5f47dec739209be6c258c93bdd39/Sampler/WikiSource/Home.md#L17)):*
> ```Markdown
> ## Prerequisites
> 
> - PowerShell 5.or higher
> ```





_Suggestion:_
```Markdown
- PowerShell 5.0 or higher
```
___
*[`Sampler/WikiSource/Home.md` line 19 at r4](https://reviewable.io/reviews/gaelcolas/Sampler/488#-O4fRP_t82fKNe8QYUUy:-O4fRP_t82fKNe8QYUUz:bdddun0) ([raw file](https://github.com/gaelcolas/Sampler/blob/0f6b04d0d0de5f47dec739209be6c258c93bdd39/Sampler/WikiSource/Home.md#L19)):*
> ```Markdown
> - PowerShell 5.or higher
> 
> The build command will download all other modules required (if you choose too) into the `RequiredModules` folder of your module project for you. 
> ```

Let us remove this text. It should instead be explained (if it is not already) in the other documentation.



_Code quote:_
```Markdown
The build command will download all other modules required (if you choose too) into the `RequiredModules` folder of your module project for you.
```


<!-- Sent from Reviewable.io -->

2026-02-09 12:40 UTC, gaelcolas commented
/azp run

2026-02-09 12:42 UTC, gaelcolas approved these changes
ok. I'll take it from here.
Please create issues for changes to the docs you think are needed.

2026-03-31 08:24 UTC, gaelcolas commented
/azp run

2026-03-31 08:33 UTC, gaelcolas approved these changes
looking good. Thanks.

2026-03-31 08:44 UTC, merged